version: 0.2

phases:
  install:
    commands:
      - echo '#!/bin/bash' > /usr/local/bin/ok; echo 'if [[ "$CODEBUILD_BUILD_SUCCEEDING" == "0" ]]; then exit 1; else exit 0; fi' >> /usr/local/bin/ok; chmod +x /usr/local/bin/ok
      #      - npm i -D puppeteer karma-chrome-launcher

  #      - echo Entered the install phase...
  #      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
  #      - yum -y install ./google-chrome-stable_current_x86_64.rpm
  #      - ln -s /usr/bin/google-chrome-stable /usr/bin/chromium

  build:
    commands:
      - ./gradlew publish --info -PBUILD_NUMBER=$CODEBUILD_BUILD_NUMBER

cache:
  paths:
    - '/root/.m2/**/*'
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'