[versions]
kotlinx-coroutines = "1.10.2"
kotlinx-serialization = "1.10.0-RC"
kotlin-test = "2.3.0"
ktor = "3.3.3"
graphql = "25.0"
aws-lambda-events = "3.16.1"
kotlin-poet = "2.2.0"

[libraries]
# KotlinX Coroutines
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

# KotlinX Serialization
kotlin-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }

# Kotlin Test
kotlin-test = { group = "org.jetbrains.kotlinx", name = "kotlin-test", version.ref = "kotlin-test" }
kotlin-test-annotations-common = { group = "org.jetbrains.kotlinx", name = "kotlin-test-annotations-common", version.ref = "kotlin-test" }
kotlin-test-junit5 = { group = "org.jetbrains.kotlinx", name = "kotlin-test-junit5", version.ref = "kotlin-test" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }

# Ktor
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }
ktor-server-core = { group = "io.ktor", name = "ktor-server-core", version.ref = "ktor" }
ktor-server-test-host = { group = "io.ktor", name = "ktor-server-test-host", version.ref = "ktor" }

# Other libraries
graphql = { group = "com.graphql-java", name = "graphql-java", version.ref = "graphql" }
aws-lambda-events = { group = "com.amazonaws", name = "aws-lambda-java-events", version.ref = "aws-lambda-events" }
kotlin-poet = { group = "com.squareup", name = "kotlinpoet", version.ref = "kotlin-poet" }
