name: Publish

on:
  push:
    branches:
    - '[0-9]+.[0-9]+.x'

permissions:
  id-token: write
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout working directory
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 17

      # validate that the gradle wrapper matches official checksums.
      - uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

      - name: Write Nexus Key
        id: nexus_gpg_file
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'nexus-key.gpg'
          encodedString: ${{ secrets.NEXUSKEY64 }}

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Gradle Build
        run: ./gradlew build

      - name: Publish
        run: ./gradlew snapshot -Psigning.keyId="${{ secrets.SIGNING_KEYID }}" -Psigning.password="${{ secrets.SIGNING_PASSWORD }}" -Psigning.secretKeyRingFile="${{ steps.nexus_gpg_file.outputs.filePath }}" -PsonatypeUsername="${{ secrets.MAVEN_CENTRAL_USER }}" -PsonatypePassword="${{ secrets.MAVEN_CENTRAL_PASSWORD }}"

      - name: Get the latest tag
        id: get_tag
        run: echo "tag=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ env.tag }}
          title: ${{ env.tag }}
          prerelease: false